#!/bin/bash -xe

project=abc80sim
if [ -z "$dir" ]; then
    dir=../rel
fi
if [ -z "$pv" ]; then
    pv="$(git describe --abbrev=4)"
fi

dir="$dir/$pv"

mkdir -p "$dir"
git archive --format=tar --prefix="$pv"/ HEAD | ( cd "$dir" && tar xvvf - )
cd "$dir"
( cd "$pv" && ./autogen.sh )
tar cvvf "$pv".tar "$pv"
xz -9ek "$pv".tar
gzip -9 "$pv".tar

# Do a native build to make sure we checked in what we were support to...
native=$(sh "$pv"/autoconf/helpers/config.guess)
# Other targets
targets='x86_64-w64-mingw32'

# Search for Windows DLLs. This tries to get the transitive closure
# of all DLLs that we use that are actually present in $dlldir.
get_dlls () {
    local x
    local f
    for x; do
	for f in $("$target"-strings $x | grep -i '\.dll$'); do
	    if [ ! -f "$f" -a -f "$dlldir"/"$f" ]; then
		cp "$dlldir"/"$f" .
		get_dlls "$f"
	    fi
	done
    done
}

for target in $native $targets; do
    (
	mkdir "$target"
	cd "$target"
	tar xf ../"$pv".tar.xz
	(
	    cd "$pv"
	    ./configure --host="$target"
	    make clean
	    make -j
	)
	dlldir=$("$target"-gcc -print-sysroot || true)/mingw/bin
	if [ -d "$dlldir" ]; then
	    mv "$pv" _build
	    mkdir "$pv"
	    cp $(find _build -type f -name '*.exe') "$pv"/
	    rm -f _build/stdout.txt _build/stderr.txt || true
	    for f in $(find _build -type f -name '*.txt'); do
		todos < "$f" > "$pv"/"$(basename "$f")"
	    done

	    ( cd "$pv" && get_dlls *.exe )
	    zip -9r -o "$pv".zip "$pv"
	fi
    )
done

ln x86_64-w64-mingw32/"$pv".zip "$pv"-win64.zip
#ln i686-w64-mingw32/"$pv".zip   "$pv"-win32.zip
