#!/bin/bash -xe

project=abc80sim
target=x86_64-w64-mingw32
dlldir="/usr/$target/sys-root/mingw/bin"

./autogen.sh
./configure --host="$target"
make clean
make -j
ver="$(sed -r -e 's/^.*\"(.*)\".*$/\1/p' -e d < patchlevel.h)"
mkdir -p win/"$project-$ver"
cd win/"$project-$ver"
cp ../../abc80.exe .
todos < ../../HELP.txt > HELP.txt
todos < ../../README > README.txt
for d in SDL.dll libwinpthread-1.dll libpng16-16.dll zlib1.dll; do
    cp "$dlldir"/"$d" .
done
cd ..
zip -9r -o "$project-$ver-win64.zip" "$project-$ver"

