.TH ZDIS l 
.SH NAME
zdis \- disassembler for Z80 cross-assembler
.SH SYNOPSIS
zdis < infile.hex
.SH DESCRIPTION
.I Zdis
reads a hex file created by
.I zmac
and produces a disassembly on stdout.
.SH SEE ALSO
zmac(l)
.SH FILES
Source is in /usr/local/src/zmac directory.
.SH BUGS
Zdis ignores the program counter field in the hex file.  Instead it assumes
that the hex file has an ORG of 0.
.sp
The man page is incomplete.  If anyone discovers more information about
using zdis, please consider helping to update the man page.
