.TH ZMAC l 
.SH NAME
zmac \- macro cross-assembler for the Zilog Z80 microprocessor
.SH SYNOPSIS
zmac [-bdefgilLmnopst] infile
.SH DESCRIPTION
The
.I Zmac
assembler is modeled after the Intel 8080 macro cross-assembler
for the Intel 8080 by Ken Borgendale.  The major features are:  Full
macro capabilities, Conditional assembly, A very flexible set of
listing options and pseudo-ops, Symbol table output, Error report,
Elimination of sequential searching, Commenting of source, Facilities
for system definiton files.
.PP
.I Zmac
assembles the specified input file (default extension .asm) and
produces a .hex output file.  The options are:
.TP 8
.B b
no binary  
.TP 8
.B d
debug  
.TP 8
.B e
error list only  
.TP 8
.B f
print if skipped lines  
.TP 8
.B g
do not list extra code  
.TP 8
.B i
do not list include files 
.TP 8
.B l
no list  
.TP 8
.B L
force listing of everything 
.TP 8
.B m
print macro expansions  
.TP 8
.B n
put line numbers off 
.TP 8
.B o
list to standard output  
.TP 8
.B p
put out four \\n's for eject 
.TP 8
.B s
don't produce a symbol list  
.TP 8
.B t
don't know what this option does
.SH SEE ALSO
zdis(l)
.SH FILES
Source is in /usr/local/src/zmac directory.
.SH BUGS
The man page is incomplete.  If anyone discovers more information about
using zmac, please consider helping to update the man page.
